### ISSUE TITLE
Client Crash mit anderer Mod

### ISSUE THREAD

**Issue by AlienGurke** [HGLabor/client-issues#100]
NoRiskClient in Kombination mit LiquidBounce crasht.

CrashLog:
[crash-2020-12-23_18.36.52-client.txt](https://github.com/copyandexecute/noriskclient-issues/files/5736457/crash-2020-12-23_18.36.52-client.txt)

In meinem Fall habe ich die latest NoRiskClient Version(23.12.) und Lb b72 genommen, ist aber egal welche LB-Version, Nightly Build oder Custom Build.
Bei allen tritt der gleiche CrashLog auf mit der gleichen Message im LauncherScreen:
Error: java.lang.NoClassDefFoundError: net/minecraft/client/renderer/entity/layers/LayerHeldItem
Exit Code: -1

**Comment by F0Xde** [comment]
Wir unterstützen keine Cheat-Clients, außerdem ist das [deren Schuld](https://github.com/CCBlueX/LiquidBounce/blob/87743a69ff8db07dc18b760dca1bcdf07c7bd303/1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/injection/forge/mixins/render/MixinLayerHeldItem.java#L42).
