### ISSUE TITLE
Perspective Mod Toggle

### ISSUE THREAD

**Issue by zRainix** [HGLabor/client-issues#108]
Man kann mit den Command .perspective den Mod nicht togglen, also wenn man .perspective eingibt steht immer "Enabled perspective". Ich weiß nicht ob das gewollt ist oder nicht.

**Comment by Kolpixx** [comment]
Hey,

versuch mal diesen Command: "`.perspective hold`" ich hoffe es klappt :+1: 

Mit freundlichen Grüßen
KolpixTV

**Comment by zRainix** [comment]
Ah okay, ich dachte wenn man ".perspective" macht, dass man den Hotkey togglet, also wenn es disablet ist, man nicht in diese Perspektive rein kommt, wenn man z.B. "R" drückt.
Danke für den Hinweis :)

**Comment by zRainix** [comment]
Ich vermute, dass es sich hierbei nicht um einen Fehler handelt, sondern, dass es so gewollt sei.
