### ISSUE TITLE
(Neuste Version) Client crashed bei Arrow Trail

### ISSUE THREAD

**Issue by zRainix** [HGLabor/client-issues#110]
Wenn man Arrow Trail auf block_crack, item_crack, oder block_dust stellt und einen Pfeil schießt crasht der Client.
Fehlermeldung:
[crash-2020-12-23_20.01.37-client.txt](https://github.com/copyandexecute/noriskclient-issues/files/5736721/crash-2020-12-23_20.01.37-client.txt)
Ps: Es gibt anscheinend keinen Effekt für item_take, also wenn man einen Pfeil schießt, sieht man keinerlei Effekte.

**Comment by copyandexecute** [comment]
Fixxed mit der kommenden Version v0.1.2
