### ISSUE TITLE
six_path ist verbuggt

### ISSUE THREAD

**Issue by BifiTek** [HGLabor/client-issues#155]
Hallo, 
Ich habe versucht das neue six_path cosmetic zu wähle. Ich hab es gemacht wie immer, und es hat sich nichts geändert. Liegt es an mir oder habe ich tatsächlich einen Bug gefunden.
LG Bifi_Tek (das ist mein Ingame Name, falls es an mir liegt)

**Comment by KeineLustAufName** [comment]
Du musst .reloadcosmetics machen

**Comment by copyandexecute** [comment]
Du benötigst die neuste Version
