### ISSUE TITLE
Dragon Wings

### ISSUE THREAD

**Issue by EinfachEhrenlos** [HGLabor/client-issues#156]
Wenn man die Dragon Wings schwarz (#000000) machen will sind sie unsichtbar.
![Dragon Wings unsichtbar](https://user-images.githubusercontent.com/76598540/103142224-16060f00-4700-11eb-8068-66e4f3adf266.png)
Man sieht ja der Spieler wird unsichtbar also hab ich sie enablet.

**Comment by KeineLustAufName** [comment]
Das liegt an der Farbe, mach einfach 000001 da sieht man keinen Unterschied

**Comment by copyandexecute** [comment]
Liegt daran dass schwarz nicht angezeigt werden kann bei dieser art von cosmetic gleiches gilt für creeper-lightning
