### ISSUE TITLE
Komischer Texturen-Bug (idk how to explain)

### ISSUE THREAD

**Issue by Jaxyx** [HGLabor/client-issues#186]
Ich habe keine Ahnung was das ist, aber da mir keine Cosmetics angezeigt werden, könnte das einen Zusammenhang haben.
![grafik](https://user-images.githubusercontent.com/76794894/103384437-b7bd9f80-4af6-11eb-940e-fa2594ce4ba4.png)
![grafik](https://user-images.githubusercontent.com/76794894/103384528-09662a00-4af7-11eb-877f-086ec1ee8fa5.png)
(das ist das inv^)
![grafik](https://user-images.githubusercontent.com/76794894/103384585-3c102280-4af7-11eb-97c3-21cd8cfb0c1b.png)
![grafik](https://user-images.githubusercontent.com/76794894/103384635-63ff8600-4af7-11eb-8b48-d3f59be5c232.png)
(Im tp sind alle Texturen außer widgets, icons und der Ladehintergrund default, daran kann es nicht liegen(ach und soups auch))

**Comment by WorldEnd0** [comment]
Eventuell liegt es an einem Texturepack?

**Comment by KeineLustAufName** [comment]
> Eventuell liegt es an einem Texturepack?

Nein ich glaube nicht ich kenne jemanden der das auch Mal hatte aber kein tp drin hatte

**Comment by WorldEnd0** [comment]
> > Eventuell liegt es an einem Texturepack?
> 
> Nein ich glaube nicht ich kenne jemanden der das auch Mal hatte aber kein tp drin hatte

Dann liegt es mit hoher Wahrscheinlichkeit an einer Falschen Installation i guess

**Comment by mooziii** [comment]
mach mal Log an und schick den Log hier rein

**Comment by Jaxyx** [comment]
Es liegt tatsächlich daran, dass versehentlich mit der falschen Version gespielt habe. Es tut mir leid, eure Zeit damit "verschwendet" zu haben. Trotzdem vielen Dank für eure Hilfe.
