### ISSUE TITLE
[idee] Server ip

### ISSUE THREAD

**Issue by CedricHuf** [HGLabor/client-issues#191]
Moin,
(m)eine idee waere das wenn man eine Server ip eingibt und sie gueltig ist das die Schriftfarbe geaendert wird.
Beispiel:
![](https://cdn.discordapp.com/attachments/774596130541142037/794216728040964136/Idee.PNG)

Idee + Screenshot von Bo.ssy 19#2785 auf dc

Grüße Stueckweise

**Comment by F0Xde** [comment]
Bruder was ist bei dir und deinen Farben los, zu viel Skittles gegessen?
