### ISSUE TITLE
Screenshot Bug

### ISSUE THREAD

**Issue by jxxelghg** [HGLabor/client-issues#193]
Ich hab Screenshot normal auf F2 eingestellt, aber immer wenn ich auf die Taste "<" komme wird ein Screenshot gemacht.
Schon getestet ist nur beim NoRisk-Clinte liegt also nicht an mir.

**Comment by Kolpixx** [comment]
Hey,

es ist immer so ,dass man weiterhin mit der "<" Taste Screenshots macht. Und du sagtest ja das es nur bei Norisk Client so ist ,aber hast du eine andere Version benutzt ,denn ich glaube in den neueren Versionen ist es nicht mehr so. Hier ist etwas was dir helfen kann:
![Screenshot](https://user-images.githubusercontent.com/68741965/103437655-38c98380-4c2a-11eb-8f69-e912fa68a891.png)
)

Mit freundlichen Grüßen
KolpixTV
