### ISSUE TITLE
Eigene Control Settings

### ISSUE THREAD

**Issue by redconcrete05** [HGLabor/client-issues#199]
Wenn ich mit dem NRC spiele benutze ich togglesprint und lege die sprinttaste auf eine andere. Wenn ich aber wieder Speedruns oder so etwas im Singleplayer machen möchte muss ich immer erst den Button wechseln. Vieleicht kann man die Settings beim Norisk Client seperat speichern oder so

**Comment by F0Xde** [comment]
Duplicate of #189
