### ISSUE TITLE
dragon wings

### ISSUE THREAD

**Issue by Blockbuster710diggadernamegehtnicht** [HGLabor/client-issues#200]
durch die wings kann man durch nether portale und eis schauen ohne die textur davon zu sehen

wenn man im f5 durch die wings in den himmel schaut werden ise unsichtbar

**Comment by Kolpixx** [comment]
Hey,

auch wenn es ein bisschen spät ist ,aber dieser Bug ist bereits bekannt. Ich denke der Bug wird bald gefixxt ,außedem siehst nur du dich unsichtbar und nicht andere Spieler.

Mit feundlichen Grüßen
Kolpix
