### ISSUE TITLE
Mouse keybind funktioniert nicht beim Sneaken 

### ISSUE THREAD

**Issue by C0nnn0r** [HGLabor/client-issues#203]
ess funktioniert nicht wen man sneakt und in seiner hotbar slott wechseln will.

**Comment by C0nnn0r** [comment]
ess funktioniert nicht wen man sneakt und in seiner hotbar slott wechseln will.

**Comment by KeineLustAufName** [comment]
Das liegt nicht am Client sondern an mc. Du musst im Treiber deiner Maus einfach deine Maustasten auf eine Zahl legen so das wenn du die Maustaste drückst es so wäre als ob du die Zahl drücken würdest. Genau das Problem hatte ich früher auch mal, aber nicht mit nrc sondern mit dem normalen mc

**Comment by C0nnn0r** [comment]
Ok werde ich machen danke für die hilfe
