### ISSUE TITLE
Swordglint und Itemsize

### ISSUE THREAD

**Issue by HATEHarmlos** [HGLabor/client-issues#205]
Swordglint und Itemsize funktionieren bei mir nicht

**Comment by g0ogo** [comment]
Itemsize = .itemsize (größe)

**Comment by KeineLustAufName** [comment]
Du musst einmal nur .itemsize machen damit itemsize an ist, bei swordglint warscheinlich das gleiche

**Comment by HATEHarmlos** [comment]
Ja ok danke itemsize funtioniert jetzt bei mir swordglint aber leider nicht
