### ISSUE TITLE
FPS werden bei Standalone falsch angezeigt

### ISSUE THREAD

**Issue by g0ogo** [HGLabor/client-issues#213]
Ich habe mir letztens die Standalone version heruntergeladen und bemerkt, das die FPS bei der FPS Mod nicht mit den eigentlichen FPS übereinstimmen. Das passiert nur wenn man über 250 fps cappt oder unlimited macht

**Comment by Kolpixx** [comment]
Hey,

dass ist bereits bekannt und ich habe auf den Discord gelesen ,dass wohl die beiden fps anzeigen (wenn man bei optifine "fps anzeigen" aktiviert) addiert werden also bei optifine steht da immer "123/57"  FPS und dann wird halt beim norisk Client 123 + 57 addiert und dann steht da 180 FPS ich bin mir nicht sicher ob es stimmt aber ich habe es halt auf den Discord gelesen. Du kannst ja einfach die Optifine FPS anzeigen lassen ,wenn du die richtigen wissen willst.

Mit freundlichen Grüßen
Kolpix

**Comment by F0Xde** [comment]
Fixed in 0.2.1
