### ISSUE TITLE
Game crashes when changing resource pack

### ISSUE THREAD

**Issue by Neffui** [HGLabor/client-issues#216]
Hallo ich habe folgende bugs bei mir und ein paar freunden gesehen sobald man das texturebpack ändert stürzt das spiel ab und swordglint funktioniert garnicht

**Comment by copyandexecute** [comment]
bitte den crashreport hochladen `.minecraft\crash-reports`

**Comment by F0Xde** [comment]
Wird erstmal geschlossen, bitte einen crashlog mit der neusten Version senden, falls das Problem immer noch auftreten sollte.
