### ISSUE TITLE
Idee

### ISSUE THREAD

**Issue by jeremy187pascal** [HGLabor/client-issues#220]
Kein Hintergrund für den Chat.
Wenn man etwas in den Chat schreibt dann ist der dunkel hinterlegt. Mit dieser funktion kann man das dunkle ausschalten

**Comment by Krxwallo** [comment]
Gibt es schon

**Comment by DoctorFuchs** [comment]
@F0Xde kann glaube geschlossen werden, wenn es das schon gibt

**Comment by copyandexecute** [comment]
`.clearbg chat`
