### ISSUE TITLE
Wings Bug

### ISSUE THREAD

**Issue by Skenz-Flow** [HGLabor/client-issues#225]
Man kann mit den Wings durch Glass "X-rayen" Bitte fixen.
![Sprinting (Toggled)](https://user-images.githubusercontent.com/78537567/106881417-cd1d7f00-66dd-11eb-8fa0-ab6f7774173e.png)
![Sprinting (Toggled)](https://user-images.githubusercontent.com/78537567/106881424-d0186f80-66dd-11eb-80fb-3658503ff09f.png)

**Comment by Kolpixx** [comment]
Hey,

der Bug ist bereits bekannt und wird denke ich bald gefixxt.

Mit freundlichen Grüßen
KolpixTV
