### ISSUE TITLE
Hypixel Kick

### ISSUE THREAD

**Issue by pascal-adk** [HGLabor/client-issues#238]
Ins Spiel gehen und mit dem Schwert blocken = Autokick bei hypixel

**Comment by Krxwallo** [comment]
Welche Version?

**Comment by pascal-adk** [comment]
1.16

**Comment by Krxwallo** [comment]
Funktioniert ".oldpvp false"?

**Comment by pascal-adk** [comment]
Ja, Sorry wusste ich nicht...
