### ISSUE TITLE
Family Safety bug

### ISSUE THREAD

**Issue by getSono** [HGLabor/client-issues#257]
Ich habe einen komplett neuen PC bekommen der eine Kindersicherung hat. Wegen der kann mein PC nicht auf `api.norisk.gg` zugreifen und es zeigt nichts an.

**Comment by bifaciall** [comment]
Da ich annehme, dass die Kindersperre gewollte ist, musst du das mit deinen Eltern klären. Man kann meines Wissens in den Einstellungen bestimmte Websites explizit erlauben. 

https://support.microsoft.com/de-de/account-billing/filtern-von-websites-und-suchvorgängen-mithilfe-von-microsoft-family-safety-3034d91e-5efa-9fbe-1384-46009f087ccf

**Comment by bifaciall** [comment]
Sollte das nicht der Fall sein kannst du auch einfach Family Safety ausschalten.
