### ISSUE TITLE
Norisk-Client Bug List

### ISSUE THREAD

**Issue by xUnleqitTV** [HGLabor/client-issues#27]
Alle Bugs die ich Bisher gefunden Habe:

-Im Inventar werden keine Maustasten akzeptiert aber in der Hotbar.

-Texturen Bug das Alle Cosmetics Pink sind (Kann NICHT behoben werden durch Client Neuinstallation).

-In den Control Options Ist die Norisk-Client Kategorie als norisk.key.category Gelistet genau so wie die dazu gehörigen Optionen.

-Mehr habe ich nicht gefunden

**Comment by copyandexecute** [comment]
please create a issue for each sub on its own
