### ISSUE TITLE
(?Mac? vllt. auch windows) Keine Speziellen Texturen

### ISSUE THREAD

**Issue by Walentinik** [HGLabor/client-issues#28]
Auch nach dem Neuinstalieren werden die Speziellen textures(kleines norisk client icon im tab, dragon wings,...) nur schwarz lila angezeigt. Ich wieß nicht warum.

**Comment by F0Xde** [comment]
Bitte volle, verständliche Sätze schreiben.

**Comment by F0Xde** [comment]
Tritt der selbe Fehler ohne andere geladene Mods auf?

**Comment by Walentinik** [comment]
> Tritt der selbe Fehler ohne andere geladene Mods auf?

Ja

**Comment by Woody1474747** [comment]
Bei mir (Mac) tretet dieses Problem auch auf.

**Comment by Woody1474747** [comment]
![Bildschirmfoto 2020-12-17 um 14 23 52](https://user-images.githubusercontent.com/71826214/102493680-d1310700-4073-11eb-92c7-cfac14b94300.png)

**Comment by Woody1474747** [comment]
Problem bei mir Behoben NoriskClient darf nicht im .minecraft Verzeichnis laufen
