### ISSUE TITLE
Game absturz

### ISSUE THREAD

**Issue by xaiyadev** [HGLabor/client-issues#32]
Mein Game Crascht random

Fehler meldung: 
`The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Unexpected error
Exit Code: 255`

Log:
[crash-2020-12-17_08.42.32-client.txt](https://github.com/copyandexecute/noriskclient-issues/files/5707712/crash-2020-12-17_08.42.32-client.txt)

**Comment by F0Xde** [comment]
Duplicate of #24
