### ISSUE TITLE
Mac Minecraft can not start

### ISSUE THREAD

**Issue by ItsSebis** [HGLabor/client-issues#33]
![Bildschirmfoto 2020-12-17 um 09 01 55](https://user-images.githubusercontent.com/59472813/102460528-6a95f400-4047-11eb-8db6-ab19da63201f.png)
It says java had a problem to start, but it worked without Norisk Client. (Mac Version: **OS X** El Capitan 10.11.6)

[crash-2020-12-17_10.17.33-client.txt](https://github.com/copyandexecute/noriskclient-issues/files/5708225/crash-2020-12-17_10.17.33-client.txt)

**Comment by ItsSebis** [comment]
Forge is installed and Optifine too.

**Comment by xaiyadev** [comment]
Lies doch mall durch und du wirst alles auf einmall verstehen!

**Comment by F0Xde** [comment]
Please add more detail if this is an actual bug (e.g. crash log, ...)

**Comment by ItsSebis** [comment]
issue is Updated with Crash log @F0Xde

**Comment by ItsSebis** [comment]
> Lies doch mall durch und du wirst alles auf einmall verstehen!

Wenn ich auf "Weitere Infos" klicke komme ich zu Adobe Flash Player und soll mir den kaufen.

**Comment by ItsSebis** [comment]
![Bildschirmfoto 2020-12-17 um 10 27 48](https://user-images.githubusercontent.com/59472813/102469051-97033d80-4052-11eb-9dd6-33bd02e28127.png)
Maybe this can help ^

**Comment by xaiyadev** [comment]
Den Eror must du lesen. Da steht: `Um das java-Befehlzeilenprogram nutzten zu können müssen Sie ein Java-Entwichleroaket installieren`

Also für dummies: Du must ein Java Entwicklerpaket installieren. Wie? Das must du selber herausfinden google es oder click auf weitere infos und mit adobe kann es **NICHTS** zu tun haben weil es **JAVA** ist. Also du must dir das installieren was da steht und fertig!

**Comment by F0Xde** [comment]
Der angefügte Log ist übrigens komplett unabhängig davon, einfach die neuste Version runterladen
