### ISSUE TITLE
Forge mit Client crasht

### ISSUE THREAD

**Issue by Altrox4q** [HGLabor/client-issues#35]
Manchmal wenn ich Multiplayer Server joine, crasht mein mein Spiel sofort mit dieser Fehlermeldung:
**The game crashed whilst rendering entity in world
Error: java.lang.IllegalStateException: Already building!
Exit Code: -1**

Dieses Problem hatte ich im normalen Minecraft Launcher oder Bac nicht.
LG Altrox_4q

**Comment by xaiyadev** [comment]
Diesen Bug gab es bereits du must einfach nur noriskclient neu installieren. Wurde bereits gefixt aber bei mir hat es erst funktioniert wo ich komplette jar neu installiert habe

LG Breaking

**Comment by Altrox4q** [comment]
Ok Danke
