### ISSUE TITLE
Minecraft crashed beim Starten (mac) 

### ISSUE THREAD

**Issue by Icefox06** [HGLabor/client-issues#38]
Wenn ich die mods wie im Tutorial einfüge und dann forge starte crashed mein minecraft. (macOS)

**Comment by F0Xde** [comment]
Bitte Crash-Log hinzufügen

**Comment by Icefox06** [comment]
![Uploading 4145A28A-2791-4F1A-9E99-1C479277E64C.jpeg…]()

**Comment by Icefox06** [comment]
![IMG_0398](https://user-images.githubusercontent.com/76157386/102475774-97073b80-405a-11eb-8495-a6bad78c5240.jpeg)
