### ISSUE TITLE
client crashed nach ".discordrpc"

### ISSUE THREAD

**Issue by Icefox06** [HGLabor/client-issues#44]
Mein Spiel ist nach dem eingeben von".discodrpc" gecrashed.

**Comment by F0Xde** [comment]
Dann gib nicht `.discordrpc` ein lol

**Comment by F0Xde** [comment]
Das Problem liegt daran, dass wenn die DiscordRPC library nicht geladen werden kann, dann wird der `discordrpc` command trotzdem registriert. Closing weil vermutlich won't fix und keine angefügten logs.
