### ISSUE TITLE
Ich kann den client nicht starten

### ISSUE THREAD

**Issue by PxXelskin** [HGLabor/client-issues#49]
wenn ich im mojang launcher den client auswähle kommt eine Meldung dass das spiel gecrashed ist

habs schon probiert mit launcher neustarten neu runterladen und pc neu starten was alles nicht geklappt hat

downloads:
Client und optifine

habe keine shader oder ähnliches an

**Comment by F0Xde** [comment]
Bitte Crash-Log anfügen
