### ISSUE TITLE
Gomme Bedwars Spieleranzahl im Scoreboard

### ISSUE THREAD

**Issue by ghost** [HGLabor/client-issues#51]
Wennn man im NoRisk Client die Nummern für das Scoreboard ausmacht, fehlen leider auch die Anzahl der Spieler in den Teams in Bedwars
![Numbers off](https://user-images.githubusercontent.com/44673644/102556360-0287f200-40c9-11eb-81c9-f916a2d60590.png)
![Numbers on](https://user-images.githubusercontent.com/44673644/102556362-03208880-40c9-11eb-9fbe-248bacd06564.png)

**Comment by F0Xde** [comment]
Du hast das System verstanden, herzlichen Glückwunsch
