### ISSUE TITLE
Custom Cape wird bei Auto Update nicht angezeigt!

### ISSUE THREAD

**Issue by th3seb** [HGLabor/client-issues#52]
Wenn man AutoUpdate aus hat wird Das Custom Cape nicht angezeigt, aber wenn man es wieder an macht und neu startet dann ist es wieder da.

**Comment by Hiveuwu** [comment]
Ich hab genau den selben fehler, weiß leider auch nicht wie man den fixt.

**Comment by F0Xde** [comment]
Bitte genauere Infos / Schritte um dies zu reproduzieren

**Comment by Hiveuwu** [comment]
Einfach auf ein auto Update warten und dann zb. auf Gomme gehen
