### ISSUE TITLE
Richtig low FPS

### ISSUE THREAD

**Issue by Sukafuu** [HGLabor/client-issues#59]
Wenn ich mit dem Norisk Client Spiele habe ich um die 30 fps aber mit badlion etc habe ich bis zu 500 fps.
![2020-12-18_07 46 04](https://user-images.githubusercontent.com/65227078/102583597-4862ab80-4105-11eb-9364-b5bbf2d3a34d.png)

**Comment by F0Xde** [comment]
Versuche Motion-Blur zu deaktivieren, ansonsten bitte mehr Details zur Verfügung stellen

**Comment by Sukafuu** [comment]
Motion Blur ist bei mir schon Deaktiviert habe alle cosmetics aus mit .cosmetics Render distance ist bei mir bei 2

**Comment by F0Xde** [comment]
Sehr ungewöhnlich, leider können wir ohne weiteres nichts dazu sagen, bei den meisten läuft ohne besondere Probleme.
Wird geschlossen bis es genauere Informationen gibt.
