### ISSUE TITLE
Sword Glint Creeper + Wither

### ISSUE THREAD

**Issue by sixGHG** [HGLabor/client-issues#64]
Bei mir kann ich Swordglint nicht aktivieren. Ich gebe ".sword_glint glint [Creeper oder Wirher]" ein aber beides funktioniert nicht. Ich sehe den Swordglint auch bei anderen Spielern nicht.

**Comment by F0Xde** [comment]
Wither ist aktuell nicht implementiert, swordglint aktivierst du wie jedes andere Modul mit `.swordglint`
