### ISSUE TITLE
NoRisk der Skidder :D

### ISSUE THREAD

**Issue by ghost** [HGLabor/client-issues#72]

**Comment by F0Xde** [comment]
Bitte mehr Details und genaue Schritte um das Problem zu reproduzieren

**Comment by ghost** [comment]
> Bitte mehr Details und genaue Schritte um das Problem zu reproduzieren

Der schaut sich um nach links aber ich beweg meine Maus halt nicht, und zufällig ist der zweite monitor bzw kann man ja einstellen auch links yk, deshalb vielleicht? kurz brain usen pls i dont wanna reply again the simple shit :D <3

**Comment by F0Xde** [comment]
Wenn du nicht bereit bist genauere Informationen zu teilen, sprich welches Betriebssystem und möglicherweise ein Video des Ganzen, kann ich dir leider nicht helfen, auf meinem System tritt nichts vergleichbares auf.

**Comment by ghost** [comment]
> Wenn du nicht bereit bist genauere Informationen zu teilen, sprich welches Betriebssystem und möglicherweise ein Video des Ganzen, kann ich dir leider nicht helfen, auf meinem System tritt nichts vergleichbares auf.

sad haha
