### ISSUE TITLE
Screenshot bug. 

### ISSUE THREAD

**Issue by Ich271** [HGLabor/client-issues#80]
Meine open Comman taste liegt auf < und mein Screenshoot auf f2 aber immer wenn ich open Command(<) drücke wird ein Screenshot genommen wenn ich aber die Screenshot Taste auf eine andere lege hab ich das Problem nicht mehr. Bei anderen Clients hab ich das Problem auch nicht.

**Comment by F0Xde** [comment]
Duplicate of #73
