### ISSUE TITLE
Dragon wings + Hex Color #000000

### ISSUE THREAD

**Issue by sixGHG** [HGLabor/client-issues#81]
Hier sieht man die Dragon 
![2020-12-18_23 52 21](https://user-images.githubusercontent.com/66011980/102668530-69baaa80-418c-11eb-9b42-449312612003.png)
Wings mit der Hex Color #000000

**Comment by sixGHG** [comment]
ist das so normal? ich vermute das es einfach schwarz sein soll

**Comment by F0Xde** [comment]
Duplicate of #45
