### ISSUE TITLE
Shoulder Pet ist falscher Skin

### ISSUE THREAD

**Issue by xHeaveny** [HGLabor/client-issues#83]
Wenn NoRisk das Skin Shoulderpet ausgewählt hat wird der Skin von einem selbst angezeigt und nicht der von dem Spieler der das pet trägt. Ich wüsste wie man es fixen könnte aber sagt bescheid wenn ihr Hilfe braucht 
Link zum Screenshot:
* [Screenshot](https://imgur.com/a/fbbt7Ok)

**Comment by F0Xde** [comment]
Auf deinem Screenshot kann ich so ungefähr gar nichts erkennen

**Comment by xHeaveny** [comment]
![image](https://user-images.githubusercontent.com/69117321/102689988-a628ed80-4202-11eb-8e78-fe07a23d6bef.png)

**Comment by copyandexecute** [comment]
Fixxed in Version 0.0.2
