### ISSUE TITLE
Update funktioniert nicht

### ISSUE THREAD

**Issue by Nikination** [HGLabor/client-issues#85]
Der Client updated nicht automatisch, sodass  zum Beipiel logos oder ähnliches nicht mehr angezeigt werden
Die Logdatei des updaters sieht hierbei so aus:

[log.txt](https://github.com/copyandexecute/noriskclient-issues/files/5719479/log.txt)

**Comment by Nikination** [comment]
Jetzt werden seit neuestem auch die Capes nicht mehr angezeigt, die Log-Datei sieht aber noch genauso aus, also alle capes, bis auf das early access cape.

**Comment by copyandexecute** [comment]
Added Cloudflare, should work now
