### ISSUE TITLE
Cape Not Appearing But...

### ISSUE THREAD

**Issue by copyandexecute** [HGLabor/client-issues#87]
Problem: 
I can see his cape 
![grafik](https://user-images.githubusercontent.com/58366920/102695057-5871ac80-4225-11eb-8aea-816ea2a8a748.png)

but he cant see his own
![grafik](https://user-images.githubusercontent.com/58366920/102695070-632c4180-4225-11eb-84ff-fbc1e2e3c6e2.png)

**Comment by Appa123-alt** [comment]
was pasirt jetzt

**Comment by copyandexecute** [comment]
![grafik](https://user-images.githubusercontent.com/58366920/102761433-2cfed700-4377-11eb-9c93-811ffe7ca7f7.png)

Fixxed with new version > 0.0.1
