### ISSUE TITLE
Cape appearing while invisible

### ISSUE THREAD

**Issue by 3Digits** [HGLabor/client-issues#88]
When you die in an gamemode like Bedwars others can still see your Cape while you're flying around. ~NicerTryBoy#3241

**Comment by copyandexecute** [comment]
![grafik](https://user-images.githubusercontent.com/58366920/102974492-edfb8d80-44fe-11eb-9860-4bf1b1cb3f43.png)
![grafik](https://user-images.githubusercontent.com/58366920/102974581-0ff51000-44ff-11eb-9880-c633170e492c.png)


Couldn't reproduce but should be fixxed with version > 0.0.1
