### ISSUE TITLE
Cosmetic Bug

### ISSUE THREAD

**Issue by ykiro19** [HGLabor/client-issues#97]
Hey,
hab nach paar Tagen mal wieder den Client gestartet und wollte auf KitPVP Cosmetics einstellen beim joinen sah ich dann das 
-> https://youtu.be/ihhi7zGeI94
Hier auch noch ein Screen aber im Video sieht man es besser.
Mehr Infos habe ich nicht weil ich nicht weiß aus welchem Grund das kommt habe nur so gestartet wie sonst.

![2020-12-23_14 29 34](https://user-images.githubusercontent.com/58809946/103000466-6a0bca80-452b-11eb-8ddb-3db56b2a6647.png)

**Comment by Kolpixx** [comment]
Hey ykiro19,

hast du denn die neuste Version von Norisk Client ,denn bei der alten Version habe ich genau das gleiche Problem mit den gleichen OpenGL Error ,wenn nicht dann würde ich die downloaden ,falls Forge bei dir nicht funktioniert würde ich warten bis die "non-forge" Version rauskommt wie "Noriskk" in seinem neuen Video erwähnte.

Mit freundlichen Grüßen
Kolpix

**Comment by Kolpixx** [comment]
Hey ykiro19,

hast du denn die neuste Version von Norisk Client ,denn bei der alten Version habe ich genau das gleiche Problem mit den gleichen OpenGL Error ,wenn nicht dann würde ich die downloaden ,falls Forge bei dir nicht funktioniert würde ich warten bis die "non-forge" Version rauskommt wie "Noriskk" in seinem neuen Video erwähnte.

Mit freundlichen Grüßen
Kolpix

**Comment by ykiro19** [comment]
Danke KolpixTV
bin bisschen Lost und hab noch mit dem ersten Release vom NoRiskClient gespielt.
Mit Forge läuft alles
