### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by UltraBlackLinux** [HGLabor/client-issues#99]
The website sais "Wait a little bit! (We are checking manuelly for nsfw content"
You should fix the typo in manually ;)

**Comment by F0Xde** [comment]
Thank you so much for helping us out, I wouldn't have noticed otherwise. Because of your tremendous help we were able to immediately fix this horrible issue, regarding a price for your honorable work you will be contacted shortly.

**Comment by UltraBlackLinux** [comment]
@F0Xde this really sounds pretty ironic lol
